### ISSUE TITLE
Check-in and Issues

### ISSUE THREAD

**Issue by faithebert** [faithebert/saas-website#1]
Hi there! Just checking in - I have my large nav and footer finished but am having trouble getting the mobile nav (hamburger button) to work. The checkbox itself won't disappear, but the other parts of it are seeming to work (the hamburger buttons, etc.).  Also inserting my finished quiz as well. Thanks so much

<img width="1068" alt="Screen Shot 2020-04-15 at 12 42 32 PM" src="https://user-images.githubusercontent.com/55109632/79368334-351b9280-7f1d-11ea-845d-7a95b6c016ad.png">
<img width="565" alt="Screen Shot 2020-04-15 at 1 27 04 PM" src="https://user-images.githubusercontent.com/55109632/79368338-377dec80-7f1d-11ea-86e1-90ae7d3ae0db.png">

@muxlowc

**Comment by faithebert** [comment]
@muxlowc

I fixed the hamburger button, but I am having trouble getting the image to stop from stretching (I put .crop on it but it doesn't help).

**Comment by muxlowc** [comment]
@faithebert which image exactly? The one in your hero banner?

**Comment by muxlowc** [comment]
You could add a class like "banner-img" and in your css, tell it to have a max-width, of like 700px or so? 
or add a class of "testimonial-img" or something and add css like above, but smaller

**Comment by faithebert** [comment]
Okay thanks very much! I wasn't sure if there were modulifier, etc classes that would do it or not. Thanks again, think I am figuring it out!
